### PR TITLE
Update DomainRoute.cs

### PR DESCRIPTION
**Pull request by weitzhandler**
Little code change

### CODE REVIEW

**Comment by JSkimming** [comment]
@weitzhandler thanks for the feedback. This was just an experiment I thought worth sharing? I'd be interested in how you're using it.

**Comment by weitzhandler** [comment]
@JSkimming 
First of all, whether I'm gonna use it directly or take out parts of it (probably what I'm gonna do), you deserve a huge hug for sharing your awesome stuff! Thank you.

What I'm up to, is developing a SaaS app (and I'm going to use your multi-tenant identity repo!! tx again).
But in my scenario, since my app will serve different organizations each with its set of isolated users, while tenants are determined by subdomain name, I'm looking for a way to bind the subdomain with the tenant id.
I found another great way for working with subdomain in [this gist](https://gist.github.com/maartenba/77ca6f9cfef50efa96ec), and I'm looking thru taking the good screws of each and tie em in my project!

**Comment by JSkimming** [comment]
@weitzhandler Thanks for the kind words, you're very welcome, I'm happy it is of use.

Good luck with the SaaS app, once released I'd love to hear how it works out. If you have any feedback on the [Identity Multitenant](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant) solution, please to send it through.

**Comment by weitzhandler** [comment]
@JSkimming I'll do!
I actually think multi-tenancy should be part of the .NET foundation. It's a technology on the run now with everything moving to the cloud and is not targeted in-the-box at all.

**Pull request merged**
